### ISSUE TITLE
Support Common Parameters

### ISSUE THREAD

**Issue by gillesdb** [RicoSuter/NSwag#1986]
Hi,

I'm using an OpenAPI 3.0.0 specification with common parameters for all methods of a path.
Example:
```
paths:
  /user/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
        description: The user ID
    get:
      summary: Gets a user by ID
      ...
    patch:
      summary: Updates an existing user with the specified ID
      ...
    delete:
      summary: Deletes the user with the specified ID
```

With this specification I observed following error: 
Newtonsoft.Json.JsonSerializationException: Unexpected initial token 'String' when populating object. Expected JSON object or array. Path ..

Thank you in advance for looking into this!
