### ISSUE TITLE
SwaggerToCSharpControllerGenerator does not support security definitions

### ISSUE THREAD

**Issue by Place1** [RicoSuter/NSwag#2055]
When I generate my controllers there are no "Authorize" attributes being added.

I'm using a swagger 2.0 spec with a security definition that looks like this (globally):

```yaml
securityDefinitions:
  bearerAuth:
    type: apiKey
    in: header
    name: Authorization
    description: my description
security:
  - bearerAuth: []
```

I've had to use my own liquid template to fix the routeprefix issue (#1386), and I was hoping I could solve this security definitions issue myself as well but unfortunately the [CSharpOperationModel](https://github.com/RicoSuter/NSwag/blob/master/src/NSwag.CodeGeneration.CSharp/Models/CSharpOperationModel.cs#L19) doesn't provide any of the required data to the template.

Perhaps the [CSharpOperationModel](https://github.com/RicoSuter/NSwag/blob/master/src/NSwag.CodeGeneration.CSharp/Models/CSharpOperationModel.cs#L19) should provide a `public bool RequiresAuthentication { get; set; }` property that can be used in-order to add the `[Authorize]` attribute.
