### ISSUE TITLE
Bug in parser - doesn't allow summary and description after path

### ISSUE THREAD

**Issue by n-alex-white** [RicoSuter/NSwag#2438]
I'm pretty sure that I've found a bug in the parser.

If you have a summary and/or description after the path in a definition as in this example from the OpenApi definition here https://swagger.io/docs/specification/paths-and-operations/

```yaml 
paths:
  /users/{id}:
    summary: Represents a user
    description: >
      This resource represents an individual user in the system.
      Each user is identified by a numeric `id`.
    get:
      ...
```

then the parser will fail. Remove that summary and description and it passes correctly. 

(it is correctly happy with summary and description after the verb, but consistently fails if they exist after the path and before the verb).

Regards,
