### ISSUE TITLE
Disable ctor parameter sorting when ClassStyle is Record

### ISSUE THREAD

**Issue by Micha-kun** [RicoSuter/NSwag#2657]
I'm generating my api client using your tool (fantastic by now) but I'm annoyed with the fact that when   ClassStyle is setted to Record, ctor parameters ignore yaml sorted items and reorder them in alphabetical order, making instantation a bother because I expect to have the same order as in yaml definition. For example:

```yaml
UpdateInternalNameCommandDto:
  type: object
  properties:
    CorrelationId:
      type: string
      format: uuid
    Headers:
      type: object
      additionalProperties:
        type: string
    Timestamp:
      type: string
      format: date-time
    AggregateId:
      type: string
      format: uuid
    InternalName:
      type: string
  required:
      - CorrelationId
      - Headers
      - Timestamp
      - AggregateId
  additionalProperties: false
```

Generates this class (observe ctor parameter order):

```c#
[System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.1.4.0 (Newtonsoft.Json v11.0.0.0)")]
public partial class UpdateInternalNameCommandDto 
{
    [Newtonsoft.Json.JsonConstructor]
    public UpdateInternalNameCommandDto(System.Guid @aggregateId,
                                        System.Guid @correlationId,
                                        System.Collections.Generic.IDictionary<string, string> @headers,
                                        string @internalName,
                                        System.DateTimeOffset @timestamp)
    {
        this.CorrelationId = @correlationId;
        this.Headers = @headers;
        this.Timestamp = @timestamp;
        this.AggregateId = @aggregateId;
        this.InternalName = @internalName;
    }

    ...
}
```

But i would prefer it like this (focus on ctor):

```c#
[System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.1.4.0 (Newtonsoft.Json v11.0.0.0)")]
public partial class UpdateInternalNameCommandDto 
{
    [Newtonsoft.Json.JsonConstructor]
    public UpdateInternalNameCommandDto(System.Guid @correlationId,
                                        System.Collections.Generic.IDictionary<string, string> @headers,
                                        System.DateTimeOffset @timestamp,
                                        System.Guid @aggregateId,
                                        string @internalName)
    {
        this.CorrelationId = @correlationId;
        this.Headers = @headers;
        this.Timestamp = @timestamp;
        this.AggregateId = @aggregateId;
        this.InternalName = @internalName;
    }

    ....
}
```

Currently, this is possible to configure?

Thank you.
