### ISSUE TITLE
CSharpGenerator generating enums with number type and default value

### ISSUE THREAD

**Issue by rolandpop** [RicoSuter/NSwag#2659]
I was generating a C# Client for pipedrive and encountered the following problem: 
The yaml: https://developers.pipedrive.com/docs/api/v1/pipedrive-api.yaml
(There are several issues i encountered; some are on pipedrive's side) 

They use multiple properties defined like: 

``` yaml
mail_link_tracking_enabled_flag:
          type: number
          description: Whether the link tracking in mail message body is enabled.
          enum:
            - 0
            - 1
          default: 0
```

this in turn would generate the following C#

``` C#
[Newtonsoft.Json.JsonProperty("mail_link_tracking_enabled_flag", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
public double Mail_link_tracking_enabled_flag { get; set; } = Services.double._0;
```

If i change the type to integer it does generate what I expected: 

``` csharp
[Newtonsoft.Json.JsonProperty("mail_link_tracking_enabled_flag", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
 public MailMessageDataMail_link_tracking_enabled_flag Mail_link_tracking_enabled_flag { get; set; } = Services.MailMessageDataMail_link_tracking_enabled_flag._0;
```
