### ISSUE TITLE
NSwag is generating anonymous type names even though they are defined

### ISSUE THREAD

**Issue by xantari** [RicoSuter/NSwag#2886]
The generated C# client code is generating Anonymous, Anonymous2, Anonymous3, etc type names when it shouldn't be because the type names are already defined in the swagger file.

How can this be fixed?

The constant contact API provides a swagger YAML file here: https://api.cc.email/v3/swagger.yaml

An example of an issue of one of the types being generated:

```
       public System.Threading.Tasks.Task<System.Collections.Generic.ICollection<Anonymous2>> RetrieveEmailAddressesAsync(Confirm_status? confirm_status, Role_code? role_code, string email_address)
        {
            return RetrieveEmailAddressesAsync(confirm_status, role_code, email_address, System.Threading.CancellationToken.None);
        }
```

Notice it says Anonymous2 instead of the correct typename for the return value.

The YAML defines the typename for this here:

```
        200:
          description: "Request successful."
          schema:
            $ref: "#/definitions/AccountEmails"
```

Which is defined as:

```
AccountEmails:
    type: "array"
    items:
      type: "object"
      properties:
        email_address:
          type: "string"
          description: "An email address associated with a Constant Contact account\
            \ owner."
          maxLength: 80
        email_id:
          type: "integer"
...
...
```

I used this as the generator config:

```
{
  "runtime": "NetCore22",
  "defaultVariables": null,
  "documentGenerator": {
    "fromDocument": {
      "json": "",
      "url": "https://api.cc.email/v3/swagger.yaml",
      "output": null
    }
  },
  "codeGenerators": {
    "openApiToCSharpClient": {
      "clientBaseClass": "ClientBase", //name of your client base class
      "configurationClass": null,
      "useBaseUrl": true,
      "generateBaseUrlProperty": false,
      "generateClientClasses": true,
      "generateClientInterfaces": true,
      "useHttpClientCreationMethod": true,
      "disposeHttpClient": true,
      "httpClientType": "System.Net.Http.HttpClient",
      "useHttpRequestMessageCreationMethod": true,
      "injectHttpClient": true,
      "clientClassAccessModifier": "public",
      "typeAccessModifier": "public", //make your models and client interfaces public
      "generateContractsOutput": true, //generate contacts in a separte file
      "contractsNamespace": "ARRT.ConstantContact.Api.Client.Contracts", //contracts namespace
      "contractsOutputFilePath": "Contracts.g.cs",
      "namespace": "ARRT.ConstantContact.Api.Client", //clients namespace
      "output": "Client.g.cs",
      "datetimetype": "System.DateTime"
    }
  }
}
```

Here is the CSPROJ:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <GenerateCode>true</GenerateCode>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <Configurations>Debug;Release;Development;Production;Staging;Preview;DevelopmentPreview</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="3.1.4" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="3.1.4" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="3.1.4" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="3.1.4" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="3.1.4" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
    <PackageReference Include="NSwag.MSBuild" Version="13.6.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="System.ComponentModel.Annotations" Version="4.7.0" />
    <PackageReference Include="System.Runtime" Version="4.3.1" />
    <PackageReference Include="System.ServiceModel.Primitives" Version="4.7.0" />
  </ItemGroup>

  <Target Name="NSwag" BeforeTargets="PrepareForBuild" Condition="'$(GenerateCode)'=='True' ">
    <Exec Command="$(NSwagExe_Core22) run nswag.json /variables:Configuration=$(Configuration)" ContinueOnError="true" />
  </Target>

</Project>

```

**Comment by dan-olsen** [comment]
I am having the same issue with a similar API definition.

**Comment by danielbecroft** [comment]
The issue looks to be that the `AccountEmails` model is defined as an array, but it's an array of an unnamed type:

```
AccountEmails:
    type: "array"
    items:
      type: "object"
      properties:
        email_address:
          type: "string"
          description: "An email address associated with a Constant Contact account\
            \ owner."
          maxLength: 80
        email_id:
          type: "integer"
...
...
```

There's nothing in the generator that can infer the name of the items inside the `AccountEmails` collection. The array type should really be referencing another named object definition, something like:

```
AccountEmails:
  type: array
  items:
    $ref: '#/components/schemas/AccountEmailModel'
```
