### ISSUE TITLE
How do I render literal XML characters in the generated C# XML Documentation tags?

### ISSUE THREAD

**Issue by stevenvolckaert** [RicoSuter/NSwag#2956]
I'm hand-writing an OpenAPI 3 spec, as the service I'd like a .NET client library (DLL) for doesn't offer an OpenAPI spec.

Paths can have a `summary` property, which is used by NSwag to generate the `<summary>Operation summary goes here</summary>` XML documentation annotation.

I'd like to render a hyperlink to the operation's online documentation. This works in the following example:

``` yml
paths:
  /api/3/contact/sync:
    post:
      operationId: Contacts_CreateOrUpdateContact
      summary: >-
        Create a contact, or update it if a contact with the specified email address already exists.
        See https://developers.activecampaign.com/reference#create-contact-sync for more information.
      externalDocs:
        description: Operation documentation
        url: https://developers.activecampaign.com/reference#create-contact-sync
    #...
```

Unfortunately, IntelliSense renders this as text, and not as a clickable hyperlink. To render it as a clickable hyperlink, the hyperlink needs to be formatted as a `<a>` tag.

However, if I change the summary in the description to the following:

``` yml
      summary: >-
        Create a contact, or update it if a contact with the specified email address already exists.
        See <a href="https://developers.activecampaign.com/reference#create-contact-sync">developers.activecampaign.com</a> for more information.
```

then this is the output:

``` csharp
/// <summary>Create a contact, or update it if a contact with the specified email address already exists. See &lt;a href="https://developers.activecampaign.com/reference#create-contact-sync"&gt;developers.activecampaign.com&lt;/a&gt; for more information.</summary>
```

**How can I render literal XML characters (`<`, `>`, etc.)?** Is this possible?
