### ISSUE TITLE
Add support for query parameters serialized as JSON

### ISSUE THREAD

**Issue by jcracknell** [RicoSuter/NSwag#3324]
Per the OpenAPI specification you can use the content map of the Parameter object to specify the serialization method used for a parameter.
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.1.0.md#parameterContent

```yaml
parameters:
  - name: query
    in: query
    content:
      application/json:
        schema:
          $ref: ...
```
