### ISSUE TITLE
Nullable properties ignored in externally referenced schema classes

### ISSUE THREAD

**Issue by craigngu** [RicoSuter/NSwag#3342]
Like if an object references a class in a different file

```
Test:
      $ref: ../testObject.yaml
```
      
and with the testObject being:

```
type: object
title: TestObject
properties:
  name:
    type: string
    nullable: true
```
    
The class generated by nswag will ignore the nullable property (while working when the class is inlined)
