### ISSUE TITLE
Multiline description results in incorrect C# documentation

### ISSUE THREAD

**Issue by epvanhouten** [RicoSuter/NSwag#3793]
When generating code using NSwag 13.15.3 on using the dotnet 6 tool the following openapi spec generates an incorrect documentation, resulting in compiler errors.

```
    WidgetMarker:
      description: Markers allow you to add visual conditional formatting for your
        graphs.
      properties:
        display_type:
          description: |
            Combination of:
              - A severity error, warning, ok, or info
              - A line type: dashed, solid, or bold
            In this case of a Distribution widget, this can be set to be `x_axis_percentile`.
          example: error dashed
          type: string
        label:
          description: Label to display over the marker.
          example: Error threshold
          type: string
        time:
          description: Timestamp for the widget.
          type: string
        value:
          description: Value to apply. Can be a single value y = 15 or a range of
            values 0 < y < 10.
          example: y = 15
          type: string
      required:
      - value
      type: object
```

That block results in the following generated code. Note that the `///` for the closing summary tag is missing:

```
/// <summary>Markers allow you to add visual conditional formatting for your graphs.</summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.15.3.0 (NJsonSchema v10.6.4.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class WidgetMarker
    {
        /// <summary>Combination of:
        /// <br/>  - A severity error, warning, ok, or info
        /// <br/>  - A line type: dashed, solid, or bold
        /// <br/>In this case of a Distribution widget, this can be set to be `x_axis_percentile`.
    </summary>
        [Newtonsoft.Json.JsonProperty("display_type", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Display_type { get; set; }

        /// <summary>Label to display over the marker.</summary>
        [Newtonsoft.Json.JsonProperty("label", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Label { get; set; }

        /// <summary>Timestamp for the widget.</summary>
        [Newtonsoft.Json.JsonProperty("time", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Time { get; set; }

        /// <summary>Value to apply. Can be a single value y = 15 or a range of values 0 &lt; y &lt; 10.</summary>
        [Newtonsoft.Json.JsonProperty("value", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Value { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties = new System.Collections.Generic.Dictionary<string, object>();

        [Newtonsoft.Json.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties; }
            set { _additionalProperties = value; }
        }

    }
```

Commenting out the `description: |` block results in valid code generation.
