### ISSUE TITLE
`null` argument causes request body with text "null"

### ISSUE THREAD

**Issue by tmds** [RicoSuter/NSwag#3839]
For this parameter:
```
        - name: "inputImage"
          in: "body"
          description: "Image content if the value `-` has been specified in fromSrc query parameter"
          schema:
            type: "string"
```
This code gets generated:
```
        public virtual async System.Threading.Tasks.Task ImageCreateAsync(string fromImage = null, string fromSrc = null, string repo = null, string tag = null, string message = null, string inputImage = null, string x_Registry_Auth = null, string platform = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
...
                    var content_ = new System.Net.Http.StringContent(Newtonsoft.Json.JsonConvert.SerializeObject(inputImage, _settings.Value));
                    content_.Headers.ContentType = System.Net.Http.Headers.MediaTypeHeaderValue.Parse("text/plain");
                    request_.Content = content_;
```
Not specifying a value for the `inputImage` parameter leads to a body that has the text `null`.
```
...\r\nContent-Type: text/plain\r\nContent-Length: 4\r\n\r\nnull
```
