### ISSUE TITLE
yaml/json generation OpenApi version mixed

### ISSUE THREAD

**Issue by rmzcn** [RicoSuter/NSwag#3943]
Hi.Generation is done with the following versions.
```
x-generator: NSwag v13.15.10.0 (NJsonSchema v10.6.10.0 (Newtonsoft.Json v13.0.0.0))
openapi: 3.0.0
```
In my scenario, I'm using an exception handling filter and I'm catching the exceptions in my application there. Then I return 500 response with a model(`ExcepitonModel`) from here. To avoid this definition at each endpoint in my application, I added an OperationProcessor as follows:

```
public class ExceptionHandlerOperationProcessor : IOperationProcessor
{
    public bool Process(OperationProcessorContext context)
    {
        var exceptionModelSchema = JsonSchema.FromType<ExceptionModel>();

        context.Document.Components.Schemas.TryAdd(nameof(ExceptionModel), exceptionModelSchema);

        context.OperationDescription.Operation.Responses.Add(new KeyValuePair<string, OpenApiResponse>(StatusCodes.Status500InternalServerError.ToString(), new OpenApiResponse()
        {
            Schema = new JsonSchema()
            {
                Reference = context.Document.Definitions.SingleOrDefault(x => x.Key == nameof(ExceptionModel)).Value
            }
        }));

        return true;
    }
}
```
The generated `ExceptionModel `schema is as follows:

```
ExceptionModel:
      title: ExceptionModel
      type: object
      additionalProperties: false
      properties:
        Code:
          type:
          - null
          - string
        Message:
          type:
          - null
          - string
        ExceptionType:
          type:
          - null
          - string
          .........
```

This type format is OpenApi 3.1 but my version is 3.0. At the same time, other schemas are created with OpenApi 3.0. Here is the output I expect, it should be like this: 

```
ExceptionModel:
      title: ExceptionModel
      type: object
      additionalProperties: false
      properties:
        Code:
          type: string
          nullable: true
        Message:
          type: string
          nullable: true
        ExceptionType:
          type: string
          nullable: true
          .........
```

Thank You.
