### ISSUE TITLE
How to set schema Title

### ISSUE THREAD

**Issue by miquelvir** [RicoSuter/NSwag#4359]
How can we set the schema title generated from a class?

I.e.

```
StudentDto:
      type: object
      title: Student  // this property here
      additionalProperties: false
```
