### ISSUE TITLE
C# Generator incorrectly appends optional GET parameter name to request URL

### ISSUE THREAD

**Issue by AnotherMuggle** [RicoSuter/NSwag#4940]
You can see the bug marked "Bug here!" in the example generated C# code.

Example YAML
```yaml
paths:
  /path1/path2/{requiredId}/{optionalId}:
    get:
      parameters:
        - in: path
          name: "requiredId"
          description: this is a required parameter
          required: true
          schema:
            type: string
        - in: path
          name: "optionalId"
          description: this is an optional parameter
          required: false
          schema:
            type: string
```

Example generated C#
```c#
// Operation Path: "path1/path2/{requiredId}/{optionalId}"
urlBuilder_.Append("path1/path2/");
urlBuilder_.Append(System.Uri.EscapeDataString(ConvertToString(requiredId, System.Globalization.CultureInfo.InvariantCulture)));
urlBuilder_.Append('/');
if (optionalId != null)
{
    urlBuilder_.Append(System.Uri.EscapeDataString(ConvertToString(optionalId, System.Globalization.CultureInfo.InvariantCulture)));
}
else
    if (urlBuilder_.Length > 0) urlBuilder_.Length--;
urlBuilder_.Append("{optionalId}"); // Bug here!

PrepareRequest(client_, request_, urlBuilder_);

var url_ = urlBuilder_.ToString();
request_.RequestUri = new System.Uri(url_, System.UriKind.RelativeOrAbsolute);
```
