### ISSUE TITLE
"Cannot inherit from sealed struct 'int'" and "Cannot resolve symbol 'XX'" in generated client code

### ISSUE THREAD

**Issue by millennIumAMbiguity** [RicoSuter/NSwag#4952]
I have two errors in the generated client code that I cannot resolve. 

based on [this document](https://apimundo.com/organizations/nuget-org/nuget-feeds/public/packages/NSwag.Generation/versions/latest), I use netframework-4.6.2
I use openapi 3.0.3
In my nswag.json, I have "runtime": "WinX64"

I get "Cannot resolve symbol 'XX'" from this generated code:
```cs
 if (status_ == 4XX)
```

I get "Cannot inherit from sealed struct 'int'" from this generated code:
```cs
[System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0))")]
public partial class SceneId : int
{

}
```

The openApi for SceneId looks like this:
```yaml
    SceneId:
      allOf:
        - $ref: "#/components/schemas/int32"
        - minimum: -1
```

 "#/components/schemas/int32" looks like this:
```yaml
    int32:
      description:
        An integer safely representable using a *signed 32-bit integer* type.
      type: integer
      minimum: -2147483648
      maximum: 2147483647
```
